### ISSUE TITLE
Erreur de cookies

### ISSUE THREAD

**Issue by ElyassCreates** [Merlode11/pronote-api#8]
Bonjour, voici le code de base sur le readme.md que j'ai modifié pour utiliser mes identifiants, sachant que j'utilise monbureaunumérique avec une connection educonnect:
```js
const pronote = require('pronote-api-maintained');

// Exemple
const url = 'https://idetablissement.index-education.net/pronote/';
const username = 'nom-dutilisateur-educonnect';
const password = 'mot-de-passe-educonnect';

async function main()
{
    const session = await pronote.login(url, username, password, "monbureaunumerique-educonnect");
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences', 
    // 'homeworks', 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
    }
});
```
Mais en executant ce code j'ai eu une erreur:
`Error: Cookie not in this host's domain. Cookie:"" Request:cas.monbureaunumerique.fr`
Pouvez-vous me dire comment régler ce problème s'il vous plait?

**Comment by Greensky-gs** [comment]
Bonjour, il se trouve que j'obtienne moi aussi cette erreur, pour le CAS Occitanie (et mon code est pareil que le tien, je suis encore en train d'essayer de me connecter).

Je n'ai pas encore trouvé de solution, mais je vous tiens au courant.

**Comment by ElyassCreates** [comment]
Les connexions aux ENT sont assez compliqués, surtout avec la mise en place d'educonnect. J'ai cependant trouvé une alternative: [Pronotepy](https://pronotepy.readthedocs.io/) (fonctionne avec Python). La connexion avec ENT/CAS avec Pronotepy ne fonctionnent pas, mais on peut aussi se connecter à partir d'un qrcode, ce qui fonctionne très bien (Dans le cas d'une erreur de connexion, il faut simplement ressayer,en gardant le qrcode ouvert)
